---
- name: Setup Zellij Config Directory
  file:
    path: "{{ zellij_config_dir }}"
    state: directory
    mode: '0755'

- name: Zellij | Copies Zellij Config | template
  template:
    src: zellij/config.yaml.j2
    dest: "{{ zellij_config_file }}"

- name: Zellij | Copies Zellij Config(KDL) | template
  template:
    src: zellij/config.kdl.j2
    dest: "{{ zellij_kdl_config_file }}"

- name: Setup Zellij Layout Directory
  file:
    path: "{{ zellij_layout_dir }}"
    state: directory
    mode: '0755'

- name: Setup Zellij Themes Directory
  file:
    path: "{{ zellij_themes_dir }}"
    state: directory
    mode: '0755'

- name: Zellij | Copies Zellij Default Layouts | template
  template:
    src: '{{ item.src }}'
    dest: "{{ zellij_layout_dir }}/{{ item.path  | regex_replace('\\.j2$', '') }}"
  with_filetree: '../templates/zellij/layouts'
  when: item.state == 'file'

- name: Zellij | Copies Zellij User Layouts | template
  vars:
    zellij_session_info: "{{ item.value.zellij_session }}"
    zellij_template_info: "{{ item.value.zellij_template }}"
    zellij_tab_info: "{{ item.value.zellij_tabs }}"
  template:
    src: zellij/layouts-template/layout.yaml.j2
    dest: "{{ zellij_layout_dir }}/{{ item.value.name  | regex_replace('\\.j2$', '') }}.yaml"
  loop: "{{ zellij_layouts | dict2items }}"

- name: Zellij | Copies Zellij User Layouts(KDL) | template
  vars:
    zellij_kdl_session_name: "{{ item.value.name }}"
    zellij_kdl_layout_info: "{{ item.value.layout_info }}"
  template:
    src: zellij/layouts-template/layout.kdl.j2
    dest: "{{ zellij_layout_dir }}/{{ item.value.name  | regex_replace('\\.j2$', '') }}.kdl"
  loop: "{{ zellij_kdl_layouts | dict2items }}"

- name: Zellij | Copies Zellij Default Themes | template
  template:
    src: '{{ item.src }}'
    dest: "{{ zellij_themes_dir }}/{{ item.path  | regex_replace('\\.j2$', '') }}"
  with_filetree: '../templates/zellij/themes'
  when: item.state == 'file'
