---
dotfiles_home: "{{ ansible_env.HOME }}"
dotfiles_user_home: "{{ ansible_env.HOME }}"
default_home_local: "{{ dotfiles_user_home }}/.local"
tool_install_dir: "{{ default_home_local }}"
tool_install_bin: "{{ tool_install_dir }}/bin"
bin_directory: "{{ tool_install_bin }}/"
xdg_share_dir: "{{ default_home_local }}/share"
xdg_config_dir: "{{ dotfiles_user_home }}/.config"
xdg_cache_dir:  "{{ dotfiles_user_home }}/.cache"
xdg_config_dirs:
  share: "{{ xdg_share_dir }}"
  config: "{{ xdg_config_dir }}"
  cache: "{{ xdg_cache_dir }}"
dot_download_dir: "{{ tool_install_dir }}/downloads"
extra_bookmarks: []
extra_bookmarks_file: "{{ extra_bookmarks | join('\n') }}"
devbox_nix_path_default: "{{ ansible_env.HOME }}/.local/share/devbox/global/default/.devbox/nix/profile/default/bin"
gcc_exe: /usr/bin/gcc
gpp_exe: /usr/bin/g++
make_exe: "make"
cargo_home: "{{ dotfiles_user_home }}/.cargo"
cargo_path: "{{ cargo_home }}/bin/"
