---
devbox_exe: "/usr/local/bin/devbox"
devbox_nix_path_default: "{{ ansible_env.HOME }}/.local/share/devbox/global/default/.devbox/nix/profile/default/bin"
devbox_dev_tools:
  - gcc
  - joplin
  - zellij
  - tmux
  - oil
  - tcsh
  - zsh
  - zoxide
  - zsh-powerlevel10k
  - atuin
  - ast-grep
  - starship
  - xcp
  - nushell
  - gum
  - glow
  - just
  - direnv
  - nix-direnv
  - rargs
  - fzf
  - tree
  - fd
  - ripgrep
  - ugrep
  - bat
  - exa
  - lsd
  - kmon
  - navi
  - skim
  - hyperfine
  - procs
  - ouch
  - sd
  - rnr
  - diskonaut
  - du-dust
  - tokei
  - bottom
  - choose
  - grex
  - curl
  - delta
  - git
  - gitAndTools.gh
  - act
  - lazygit
  - gitflow
  - gitui
  - gitoxide
  - soft-serve
  - diffr
  - difftastic
  - python39Packages.pipx
  - btop
  - clifm
  - ranger
  - xplr
  - yazi
  - joshuto
  - eva
  - erdtree
  - felix
  - fend
  - gotop
  - screenfetch
  - macchina
  - mprocs
  - jq
  - yq
  - fx
  - nnn
  - fff
  - ghq
  - broot
  - lf
  - glances
  - watchman
  - aspell
  - bc
  - gdb
  - emscripten
  - nox
  - cookiecutter
  - helix
  - neovim
  - neovim-remote
  - tree-sitter
  - python39Packages.pynvim
  - nodejs
  - yarn
  - ctags
  - nodePackages.prettier
  - nodePackages.bash-language-server
  - nodePackages.yaml-language-server
  - sumneko-lua-language-server
  - shfmt
